### PR TITLE
OpenDSSDirect.py API implementation using dss_capi and dss_python/CFFI

### PR DESCRIPTION
**Pull request by PMeira**
All basic tests successfully run on Windows, Linux and MacOS. Docs and setup.py still need updates.
I will release a new dss_python version to go along with this soon.

### CODE REVIEW

**Comment by kdheepak** [comment]
Wow! This is great! I'll test it now.

**Comment by PMeira** [comment]
Just reinstalled with the dss_python 0.9.8 binary from PyPI, all tests still pass on the three platforms. I think we're good to go!

**Comment by PMeira** [comment]
Looked into the AppVeyor and Travis failures, it was just that I didn't upload Python 3.5 wheels on Windows and Mac. 

Fixed that now, uploaded the missing wheels for MacOS (Python 2.7, 3.5 and 3.7), and Windows (Python 3.5 x86/x64).

**Comment by kdheepak** [comment]
Looks great! I've restarted the appveyor builds. Once the tests pass, I'll merge, update the README and tag a release.

**Comment by PMeira** [comment]
Oops, sorry, I started a separate build but already deleted it so it doesn't show up here instead of yours.

**Comment by kdheepak** [comment]
Not sure what happened, but the build seems to be deleted. I'm still able to see the build status though, so I'll wait to see results and post here.

**Comment by kdheepak** [comment]
[Tests all pass](https://ci.appveyor.com/project/kdheepak/opendssdirect-py/build/1.0.153)!

**Pull request merged**
